import { buildCard } from "@/lib/scoring/engine";
import type { Card, Signals } from "@/lib/scoring/types";
import type { BentoMarketMeta } from "@/lib/scoring/types";

// Baked Bento.fun demo markets — prediction + versus only.
// Live catalog replaces these on the home fan when BENTO_BUILDER_API_KEY is set.

const AVATAR =
  "data:image/svg+xml;utf8," +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" width="320" height="320"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="%2339d353"/><stop offset="1" stop-color="%23006d32"/></linearGradient></defs><rect width="320" height="320" fill="%2312101c"/><circle cx="160" cy="130" r="58" fill="url(%23g)" fill-opacity="0.55"/></svg>',
  );

type Sample = Signals & { market: BentoMarketMeta };

const RAW: Sample[] = [
  {
    login: "demo-btc-100k",
    name: "BTC Hits 100k",
    avatarUrl: AVATAR,
    location: "Crypto",
    followers: 9200,
    account_age_years: 0.8,
    public_repos: 4,
    total_stars_owned: 52000,
    max_repo_stars: 28000,
    languages: 3,
    rankedLanguages: ["Crypto", "BTC", "Prediction"],
    topLanguage: "Crypto",
    recent_contributions: 3400,
    active_days_recent: 210,
    active_years: 1,
    total_contributions_lifetime: 14000,
    prs_to_others: 140,
    reviews: 100,
    issues_closed: 35,
    recent_commits: 3000,
    recent_spike: true,
    market: {
      duelId: "demo-btc-100k",
      dbId: "demo-btc-100k",
      duelType: "prediction",
      options: ["Yes", "No"],
      collateralMode: "credits",
      totalBetAmountUsdc: 18400,
      uniqueParticipants: 980,
      status: 1,
      category: "Crypto",
      description: "Prediction market — will Bitcoin print $100k this year?",
      endsIn: 86400 * 45,
      question: "Will BTC hit $100k this year?",
    },
  },
  {
    login: "demo-fed-cut",
    name: "Fed Rate Cut",
    avatarUrl: AVATAR,
    location: "Macro",
    followers: 6100,
    account_age_years: 1.1,
    public_repos: 5,
    total_stars_owned: 26000,
    max_repo_stars: 12000,
    languages: 4,
    rankedLanguages: ["Macro", "Rates", "Prediction"],
    topLanguage: "Macro",
    recent_contributions: 1900,
    active_days_recent: 150,
    active_years: 2,
    total_contributions_lifetime: 9500,
    prs_to_others: 90,
    reviews: 60,
    issues_closed: 24,
    recent_commits: 1700,
    recent_spike: false,
    market: {
      duelId: "demo-fed-cut",
      dbId: "demo-fed-cut",
      duelType: "prediction",
      options: ["Yes", "No"],
      collateralMode: "credits",
      totalBetAmountUsdc: 9600,
      uniqueParticipants: 520,
      status: 1,
      category: "Macro",
      description: "Will the Fed cut rates at the next meeting?",
      endsIn: 86400 * 18,
      question: "Fed cuts rates next meeting?",
    },
  },
  {
    login: "demo-lakers-celtics",
    name: "Lakers vs Celtics",
    avatarUrl: AVATAR,
    location: "Sports",
    followers: 12800,
    account_age_years: 1.6,
    public_repos: 3,
    total_stars_owned: 64000,
    max_repo_stars: 31000,
    languages: 2,
    rankedLanguages: ["Sports", "NBA"],
    topLanguage: "Sports",
    recent_contributions: 4100,
    active_days_recent: 280,
    active_years: 2,
    total_contributions_lifetime: 22000,
    prs_to_others: 210,
    reviews: 160,
    issues_closed: 48,
    recent_commits: 3800,
    recent_spike: true,
    market: {
      duelId: "demo-lakers-celtics",
      dbId: "demo-lakers-celtics",
      duelType: "versus",
      options: ["Lakers", "Celtics"],
      collateralMode: "credits",
      totalBetAmountUsdc: 27100,
      uniqueParticipants: 1450,
      status: 1,
      category: "Sports",
      description: "Versus market — pick a side and trade the board.",
      endsIn: 86400 * 2,
      question: "Lakers vs Celtics — who wins?",
    },
  },
  {
    login: "demo-ai-ipo",
    name: "AI Lab IPO",
    avatarUrl: AVATAR,
    location: "Tech",
    followers: 3400,
    account_age_years: 0.5,
    public_repos: 4,
    total_stars_owned: 11000,
    max_repo_stars: 5000,
    languages: 3,
    rankedLanguages: ["Tech", "AI", "Prediction"],
    topLanguage: "Tech",
    recent_contributions: 1100,
    active_days_recent: 100,
    active_years: 1,
    total_contributions_lifetime: 4200,
    prs_to_others: 45,
    reviews: 28,
    issues_closed: 14,
    recent_commits: 900,
    recent_spike: false,
    market: {
      duelId: "demo-ai-ipo",
      dbId: "demo-ai-ipo",
      duelType: "prediction",
      options: ["Yes", "No"],
      collateralMode: "credits",
      totalBetAmountUsdc: 3800,
      uniqueParticipants: 240,
      status: 1,
      category: "Tech",
      description: "Will a major AI lab file for IPO this year?",
      endsIn: 86400 * 120,
      question: "Major AI lab IPO this year?",
    },
  },
];

export const SAMPLE_CARDS: Card[] = RAW.map(({ market, ...signals }) => {
  const card = buildCard(signals);
  return { ...card, market };
});

export const SAMPLE_LOGINS = RAW.map((r) => r.login);
